/// Static currency metadata: ISO code → full name.
/// A curated subset of the currencies available from open.er-api.com —
/// the ECB majors plus the currencies of frequently travelled destinations.
/// Not every code the API returns is listed here on purpose: a searchable
/// list is more useful than a complete one.
class CurrencyData {
  static const Map<String, String> currencies = {
    'AED': 'UAE Dirham',
    'ALL': 'Albanian Lek',
    'ARS': 'Argentine Peso',
    'AUD': 'Australian Dollar',
    'BAM': 'Bosnian Convertible Mark',
    'BGN': 'Bulgarian Lev',
    'BRL': 'Brazilian Real',
    'CAD': 'Canadian Dollar',
    'CHF': 'Swiss Franc',
    'CLP': 'Chilean Peso',
    'CNY': 'Chinese Yuan',
    'COP': 'Colombian Peso',
    'CRC': 'Costa Rican Colón',
    'CZK': 'Czech Koruna',
    'DKK': 'Danish Krone',
    'DOP': 'Dominican Peso',
    'EGP': 'Egyptian Pound',
    'EUR': 'Euro',
    'FJD': 'Fijian Dollar',
    'GBP': 'British Pound',
    'GEL': 'Georgian Lari',
    'HKD': 'Hong Kong Dollar',
    'HUF': 'Hungarian Forint',
    'IDR': 'Indonesian Rupiah',
    'ILS': 'Israeli Shekel',
    'INR': 'Indian Rupee',
    'ISK': 'Icelandic Króna',
    'JOD': 'Jordanian Dinar',
    'JPY': 'Japanese Yen',
    'KES': 'Kenyan Shilling',
    'KHR': 'Cambodian Riel',
    'KRW': 'South Korean Won',
    'LAK': 'Lao Kip',
    'LKR': 'Sri Lankan Rupee',
    'MAD': 'Moroccan Dirham',
    'MUR': 'Mauritian Rupee',
    'MVR': 'Maldivian Rufiyaa',
    'MXN': 'Mexican Peso',
    'MYR': 'Malaysian Ringgit',
    'NOK': 'Norwegian Krone',
    'NPR': 'Nepalese Rupee',
    'NZD': 'New Zealand Dollar',
    'PEN': 'Peruvian Sol',
    'PHP': 'Philippine Peso',
    'PLN': 'Polish Złoty',
    'QAR': 'Qatari Riyal',
    'RON': 'Romanian Leu',
    'RSD': 'Serbian Dinar',
    'SAR': 'Saudi Riyal',
    'SEK': 'Swedish Krona',
    'SGD': 'Singapore Dollar',
    'THB': 'Thai Baht',
    'TND': 'Tunisian Dinar',
    'TRY': 'Turkish Lira',
    'TWD': 'New Taiwan Dollar',
    'TZS': 'Tanzanian Shilling',
    'USD': 'United States Dollar',
    'VND': 'Vietnamese Dong',
    'XPF': 'CFP Franc',
    'ZAR': 'South African Rand',
  };

  static const List<String> defaultCurrencies = [
    'EUR',
    'USD',
    'GBP',
    'CHF',
    'JPY',
  ];
}
